version: '3.8'

services:
  oracle-price-server:
    image: dochain/oracle-price-server
    restart: always
    ports:
      - "8532:8532"
    networks:
      - dochain

  oracle-feeder:
    image: dochain/oracle-feeder
    environment:
      - ORACLE_FEEDER_DATA_SOURCE_URL=http://oracle-price-server:8532/latest
      - ORACLE_FEEDER_PASSWORD=password
      - ORACLE_FEEDER_MNEMONIC=word1 word2 word3 ...
      - ORACLE_FEEDER_VALIDATORS=dovaloper1...
      - ORACLE_FEEDER_CHAIN_ID=dochain-1
      - ORACLE_FEEDER_ADDR_PREFIX=do
      - ORACLE_FEEDER_LCD_ADDRESS=http://host.docker.internal:1317
    restart: always
    networks:
      - dochain

networks:
  dochain:
    driver: bridge